-- Auto-generated by Tactus. Do not edit.
import Lean
set_option linter.unusedVariables false
set_option maxHeartbeats 800000

-- Classical logic: Tactus specs are Prop-valued (mirroring Verus's
-- spec-mode semantics), and exec fn WP goals embed them inside `if
-- <Prop> then … else …` expressions. The `if/ite` elaborator requires
-- `[Decidable P]` for each such P. For match-defined discriminators
-- like `Type.isFoo` (synthesized by `datatype_to_cmds` for multi-
-- variant inductives) Lean doesn't derive Decidable automatically, so
-- we promote all Props to Decidable via Classical. Cost: `decide`
-- won't reduce through these to concrete truth values, but exec-fn
-- automation already uses `omega` / `simp_all` rather than `decide`.
open Classical in
attribute [instance] Classical.propDecidable

-- Architecture word size for `usize` / `isize`. Kept as an opaque
-- `Nat` plus a validity axiom — concrete values come from the build
-- target. `IntegerTypeBound::ArchWordBits` renders as `arch_word_bits`;
-- `usize::MAX` / `isize::MAX` etc. reduce to expressions over it. For
-- now `type_bound_predicate` does *not* emit refinement bounds for
-- `usize`/`isize`, because tactus_auto's current toolbox can't reason
-- about symbolic exponents (`2 ^ arch_word_bits`). See DESIGN.md
-- "Fixed-width types" for the tradeoff.
axiom arch_word_bits : Nat
axiom arch_word_bits_valid : arch_word_bits = 32 ∨ arch_word_bits = 64

-- Upper bounds for `usize` / `isize`, used as the refinement target
-- by `type_bound_predicate` in sst_to_lean.
--
-- We define them in `Int` rather than `Nat` so the resulting
-- refinement (`0 ≤ e ∧ e < usize_hi` etc.) composes cleanly with
-- `e : Int` without coercion clutter. tactus_auto can't generally
-- discharge these symbolically — proofs involving `usize` / `isize`
-- arithmetic will often need an explicit `cases arch_word_bits_valid`
-- step. That's the accepted trade-off for having the bounds be
-- present at all.
noncomputable def usize_hi : Int := (2 : Int) ^ arch_word_bits
noncomputable def isize_hi : Int := (2 : Int) ^ (arch_word_bits - 1)

-- `tactus_first | t1 | t2 | …` desugars to `first | (t1; done) |
-- (t2; done) | …`. Each alternative is required to fully close
-- the goal — without `done`, a tactic that succeeds while
-- leaving unsolved subgoals (e.g., `simp_all` in some
-- configurations) commits early and blocks later alternatives.
-- `tactus_first` makes the closure contract explicit at the
-- combinator name rather than relying on every alternative to
-- remember to append `; done`.
syntax "tactus_first" ("|" tacticSeq)+ : tactic
macro_rules
  | `(tactic| tactus_first $[| $ts:tacticSeq]*) => do
    let wrapped ← ts.mapM (fun t => `(tacticSeq| ($t:tacticSeq); done))
    `(tactic| first $[| $wrapped:tacticSeq]*)

-- `tactus_case_split closer`: try each user-datatype-typed
-- local in turn, running `closer` on each subgoal produced by
-- `cases`. Commit the first candidate where `closer` closes ALL
-- subgoals; restore state and try the next candidate
-- otherwise. Throws if no candidate works (so it composes with
-- `tactus_first` / `first` for fallthrough).
--
-- "User datatype" is gated on having a companion `.height` fn
-- (emitted by `to_lean_fn::height_fn_for_datatype` for every
-- concrete non-generic datatype — see DESIGN.md "Non-int
-- decreases"). This filters out `Int` / `Nat` / `Bool` /
-- `Option` / core types that have their own automation (omega)
-- and would explode the subgoal count if case-split.
--
-- Trying each candidate (rather than just the first) means a fn
-- with multiple datatype locals — e.g., `(a: Foo, b: Bar)` —
-- works regardless of which one is the right scrutinee. Cost is
-- O(n_candidates × closer_cost), bounded by the locals in
-- scope.
open Lean Elab Tactic Meta in
elab "tactus_case_split" closer:tacticSeq : tactic => do
  let goal ← getMainGoal
  let candidates ← goal.withContext do
    let ctx ← getLCtx
    let mut out : Array LocalDecl := #[]
    for decl in ctx do
      if decl.isImplementationDetail then continue
      let ty ← whnf decl.type
      if let .const name _ := ty.getAppFn then
        let env ← getEnv
        if let some info := env.find? name then
          if info matches .inductInfo _ then
            let heightName := Name.str name "height"
            if env.find? heightName |>.isSome then
              out := out.push decl
    return out
  for decl in candidates do
    let saved ← saveState
    try
      let subgoals ← goal.cases decl.fvarId
      setGoals (subgoals.map (·.mvarId)).toList
      evalTactic (← `(tactic| all_goals ($closer)))
      -- All goals closed if we got here.
      return
    catch _ =>
      restoreState saved
  throwError "tactus_case_split: no datatype-local case-split closes the goal"

-- `tactus_usize_bound`: discharge a goal involving `usize_hi` /
-- `isize_hi` (i.e., `2 ^ arch_word_bits` or `2 ^ (arch_word_bits -
-- 1)`) by case-splitting on `arch_word_bits_valid` and reducing
-- the resulting concrete `2 ^ 32` / `2 ^ 64` literals. The
-- `tactus_auto` toolbox (rfl/decide/omega/simp_all) can't handle
-- symbolic exponents, so usize/isize arithmetic obligations
-- normally need an explicit `proof { tactus_usize_bound }` block.
--
-- Order of operations:
-- 1. `rcases` arch_word_bits_valid into the two literal cases.
-- 2. `subst` substitutes 32 or 64 throughout the goal.
-- 3. `simp_all only [usize_hi, isize_hi]` unfolds the defs to
--    expose the `2 ^ ...` literal.
-- 4. `decide` (for purely-arithmetic-on-literals goals) or
--    `omega` (for linear-arith with the literal as a constant)
--    closes the case.
--
-- Composes with `tactus_first` so users can layer it: e.g.,
-- `tactus_first | tactus_auto | tactus_usize_bound | ...`.
macro "tactus_usize_bound" : tactic => `(tactic|
  rcases arch_word_bits_valid with h | h <;>
    (subst h; simp only [usize_hi, isize_hi]; first | decide | omega))

-- Tactus: the *atomic closer* used at the leaves of the tactics we emit.
-- Intentionally kept to simple, always-closing tactics — `rfl`,
-- `decide`, `omega`, `simp_all`, and `tactus_case_split` for goals
-- that need case analysis on a user datatype (recursive-enum fns,
-- #58).
--
-- Any structural peeling (`refine ⟨?_, ?_⟩`, `intros`, etc.) is the
-- codegen's job, not this macro's: the emitter knows exactly what
-- goal shape each theorem has, and wraps the right structural
-- tactics around `tactus_auto` calls. See `sst_to_lean`'s loop-
-- theorem emission.
--
-- `tactus_first` enforces that each alternative closes the goal
-- (wraps each in `; done`), preventing partial-success tactics
-- like `simp_all` from blocking later alternatives.
--
-- `fail` turns "nothing worked" into a real error instead of a `sorry`.
macro "tactus_auto" : tactic => `(tactic|
  tactus_first
    | rfl
    | decide
    | omega
    | simp_all
    | tactus_case_split (simp_all <;> first | omega | done)
    | tactus_case_split (simp_all)
    | fail "tactus: auto-tactic failed — add explicit proof block")

-- Recursively peel goal structure: split any top-level `∧`, introduce
-- any leading `∀` / `→`, and recurse on the resulting subgoals. Each
-- branch either removes one layer of the goal tree or hits a leaf and
-- exits via `skip`, so termination is bounded by goal size.
--
-- Used by the tactic we emit for exec fns that contain loops — those
-- produce goals shaped like `init ∧ maintain ∧ use`, with nested
-- `∀ (v : T), bounds → ...` inside each conjunct. Sequential / nested
-- loops stack the same structure, so a bounded-depth peeler would
-- have to guess the bound; recursion just follows the structure.
syntax "tactus_peel" : tactic
macro_rules
  | `(tactic| tactus_peel) => `(tactic|
      first
        | (apply And.intro <;> tactus_peel)
        -- Destructure conjunctive hypotheses on intro so leaf tactics
        -- that can't split `∧`-hypotheses themselves (not omega — it
        -- handles them — but future additions like `linarith` /
        -- `positivity`) get each conjunct as its own hypothesis.
        -- Matched before plain `intro _` so conjunctions go this path.
        | (intro ⟨_, _⟩; tactus_peel)
        | (intro _; tactus_peel)
        | skip)
