-- Auto-generated by Tactus. Do not edit.
import Lean
set_option linter.unusedVariables false
set_option maxHeartbeats 800000

-- Classical logic: Tactus specs are Prop-valued (mirroring Verus's
-- spec-mode semantics), and exec fn WP goals embed them inside `if
-- <Prop> then … else …` expressions. The `if/ite` elaborator requires
-- `[Decidable P]` for each such P. For match-defined discriminators
-- like `Type.isFoo` (synthesized by `datatype_to_cmds` for multi-
-- variant inductives) Lean doesn't derive Decidable automatically, so
-- we promote all Props to Decidable via Classical. Cost: `decide`
-- won't reduce through these to concrete truth values, but exec-fn
-- automation already uses `omega` / `simp_all` rather than `decide`.
open Classical in
attribute [instance] Classical.propDecidable

-- Architecture word size for `usize` / `isize`. Kept as an opaque
-- `Nat` plus a validity axiom — concrete values come from the build
-- target. `IntegerTypeBound::ArchWordBits` renders as `arch_word_bits`;
-- `usize::MAX` / `isize::MAX` etc. reduce to expressions over it. For
-- now `type_bound_predicate` does *not* emit refinement bounds for
-- `usize`/`isize`, because tactus_auto's current toolbox can't reason
-- about symbolic exponents (`2 ^ arch_word_bits`). See DESIGN.md
-- "Fixed-width types" for the tradeoff.
axiom arch_word_bits : Nat
axiom arch_word_bits_valid : arch_word_bits = 32 ∨ arch_word_bits = 64

-- Upper bounds for `usize` / `isize`, used as the refinement target
-- by `type_bound_predicate` in sst_to_lean.
--
-- We define them in `Int` rather than `Nat` so the resulting
-- refinement (`0 ≤ e ∧ e < usize_hi` etc.) composes cleanly with
-- `e : Int` without coercion clutter. tactus_auto can't generally
-- discharge these symbolically — proofs involving `usize` / `isize`
-- arithmetic will often need an explicit `cases arch_word_bits_valid`
-- step. That's the accepted trade-off for having the bounds be
-- present at all.
noncomputable def usize_hi : Int := (2 : Int) ^ arch_word_bits
noncomputable def isize_hi : Int := (2 : Int) ^ (arch_word_bits - 1)

-- `tactus_case_split`: find the first hypothesis of user-datatype
-- type and case-split on it. "User-datatype" is gated on having a
-- companion `.height` fn (which `to_lean_fn::height_fn_for_datatype`
-- emits for every concrete non-generic datatype — see DESIGN.md
-- "Non-int decreases"). This gate filters out `Int` / `Nat` /
-- `Bool` / `Option` / core types that have their own automation
-- (omega) and would explode the subgoal count if case-split.
--
-- No-op (succeeds with unchanged goal) if no such hypothesis
-- exists — safe to compose with other tactics in `first` /
-- `<;>` chains.
open Lean Elab Tactic Meta in
elab "tactus_case_split" : tactic => do
  let goal ← getMainGoal
  let newGoals ← goal.withContext do
    let ctx ← getLCtx
    let mut result : List MVarId := [goal]
    for decl in ctx do
      if decl.isImplementationDetail then continue
      let ty ← whnf decl.type
      if let .const name _ := ty.getAppFn then
        let env ← getEnv
        if let some info := env.find? name then
          if info matches .inductInfo _ then
            -- Gate: only split types for which we've emitted a
            -- `.height` companion (i.e., our user datatypes).
            let heightName := Name.str name "height"
            if env.find? heightName |>.isNone then continue
            try
              let subgoals ← goal.cases decl.fvarId
              return subgoals.map (·.mvarId) |>.toList
            catch _ => pure ()
    return result
  replaceMainGoal newGoals

-- Tactus: the *atomic closer* used at the leaves of the tactics we emit.
-- Intentionally kept to simple, always-closing tactics — `rfl`,
-- `decide`, `omega`, `simp_all`, and `tactus_case_split <;> simp_all
-- <;> omega` for goals that need case analysis on a user datatype
-- (recursive-enum fns, #58).
--
-- Any structural peeling (`refine ⟨?_, ?_⟩`, `intros`, etc.) is the
-- codegen's job, not this macro's: the emitter knows exactly what
-- goal shape each theorem has, and wraps the right structural
-- tactics around `tactus_auto` calls. See `sst_to_lean`'s loop-
-- theorem emission.
--
-- Each alternative is wrapped with `done` — without it, `simp_all`
-- can succeed having made progress but left unsolved subgoals,
-- blocking `first` from trying later alternatives. `done` forces
-- the closure check: if the tactic didn't fully close the goal,
-- treat it as a failure so the next alternative is tried.
--
-- `fail` turns "nothing worked" into a real error instead of a `sorry`.
macro "tactus_auto" : tactic => `(tactic|
  first
    | (rfl; done)
    | (decide; done)
    | (omega; done)
    | (simp_all; done)
    | (tactus_case_split <;> simp_all <;> (first | omega | done))
    | (tactus_case_split <;> simp_all; done)
    | (fail "tactus: auto-tactic failed — add explicit proof block"))

-- Recursively peel goal structure: split any top-level `∧`, introduce
-- any leading `∀` / `→`, and recurse on the resulting subgoals. Each
-- branch either removes one layer of the goal tree or hits a leaf and
-- exits via `skip`, so termination is bounded by goal size.
--
-- Used by the tactic we emit for exec fns that contain loops — those
-- produce goals shaped like `init ∧ maintain ∧ use`, with nested
-- `∀ (v : T), bounds → ...` inside each conjunct. Sequential / nested
-- loops stack the same structure, so a bounded-depth peeler would
-- have to guess the bound; recursion just follows the structure.
syntax "tactus_peel" : tactic
macro_rules
  | `(tactic| tactus_peel) => `(tactic|
      first
        | (apply And.intro <;> tactus_peel)
        -- Destructure conjunctive hypotheses on intro so leaf tactics
        -- that can't split `∧`-hypotheses themselves (not omega — it
        -- handles them — but future additions like `linarith` /
        -- `positivity`) get each conjunct as its own hypothesis.
        -- Matched before plain `intro _` so conjunctions go this path.
        | (intro ⟨_, _⟩; tactus_peel)
        | (intro _; tactus_peel)
        | skip)
