-- Auto-generated by Tactus. Do not edit.
set_option linter.unusedVariables false
set_option maxHeartbeats 800000

-- Architecture word size for `usize` / `isize`. Kept as an opaque
-- `Nat` plus a validity axiom — concrete values come from the build
-- target. `IntegerTypeBound::ArchWordBits` renders as `arch_word_bits`;
-- `usize::MAX` / `isize::MAX` etc. reduce to expressions over it. For
-- now `type_bound_predicate` does *not* emit refinement bounds for
-- `usize`/`isize`, because tactus_auto's current toolbox can't reason
-- about symbolic exponents (`2 ^ arch_word_bits`). See DESIGN.md
-- "Fixed-width types" for the tradeoff.
axiom arch_word_bits : Nat
axiom arch_word_bits_valid : arch_word_bits = 32 ∨ arch_word_bits = 64

-- Tactus: auto-tactic used by sst_to_lean when emitting exec fn obligations.
--
-- Peel away every `∧` split and `∀`/`→` intro across all open goals, then
-- close each arithmetic leaf with rfl / decide / omega / simp_all. This
-- single sequence handles both the flat-goal shapes from straight-line
-- exec fns and the nested `∀ … → … → A ∧ (B ∧ C)` shapes that come out
-- of loops (see `sst_to_lean`'s "Loop obligations" note).
--
-- `repeat'` applies its argument to every open goal until it stops making
-- progress. `all_goals` then runs the finisher on each leaf. If any leaf
-- can't be closed, the whole tactic fails and the user sees the
-- unresolved subgoal.
-- First pass: `try simp_all` normalizes `let x := n` and trivial
-- conjuncts like `n ≤ n`. It always succeeds (even as a no-op), so
-- the `first …` block below always gets to pick a real closer.
-- That's important: without `try`, `first | … | simp_all | …` would
-- stop at simp_all even when simp_all simplified but didn't close.
--
-- The `refine ⟨?_, ?_⟩ <;> intros <;> omega`-style branches handle
-- loop goals shaped like `maintain ∧ use`, or nested `init ∧ maintain
-- ∧ use`. Omega handles the propositional leaves (it splits hypothesis
-- `And`s and handles top-level `∧`/`→` in goals, but doesn't
-- introduce `∀`).
macro "tactus_auto" : tactic => `(tactic|
  (try simp_all);
  first
    | rfl
    | decide
    | omega
    | (intros; omega)
    | (refine ⟨?_, ?_⟩ <;> intros <;> omega)
    | (refine ⟨?_, ?_, ?_⟩ <;> intros <;> omega)
    | (refine ⟨?_, ?_⟩ <;> intros <;>
        (first | omega | (refine ⟨?_, ?_⟩ <;> intros <;> omega)))
    | (fail "tactus: auto-tactic failed — add explicit proof block"))
