-- TactusDefs.lean — Tactus's Lean vocabulary: defs, instances,
-- decoration types, the arch-word axiom pair, and the axiom-closure
-- enforcement command. NO tactics (B5, DESIGN-transparent-automation.md
-- §5): this is the file in the trust/audit story. Artifacts in the
-- default/replay emission import this module alone; the search ladder
-- lives in TactusSearch.lean (discover-mode / user tactic texts only).
--
-- (Split from the former TactusPrelude.lean, 2026-07-17.)
-- Auto-generated by Tactus. Do not edit.
-- `Lean.Elab.Command` (not the full `Lean` umbrella): its transitive
-- closure carries every elaborator the emitted artifacts use — the
-- core tactic set (simp/omega/decide/…), deriving handlers, and the
-- `elab` command machinery for `#tactus_check_axioms` — at roughly
-- half the per-process import cost of `import Lean` (~0.9s saved per
-- `lean` invocation, and every generated file pays this import).
-- `bv_decide` is NOT in this closure; TactusSearch imports it.
import Lean.Elab.Command
set_option linter.unusedVariables false
set_option maxHeartbeats 800000

-- Tactus renders Verus's u8/u16/u32/u64/u128 as `Int` (with a
-- separate `0 ≤ x ∧ x < 2^n` bound hypothesis). The arithmetic
-- ops on Int have natural typeclass instances; the bitwise ops
-- (`^^^`, `&&&`, `|||`, `>>>`, `<<<`) do NOT — Lean doesn't have
-- `HXor Int Int Int` etc. by default.
--
-- For files that use `assert(P) by(bit_vector)` (#111), Verus's
-- ast_to_sst pre-inserts a `StmX::Assume(ens)` before the
-- `StmX::AssertBitVector` — and `ens` is rendered in Int mode
-- by the surrounding pipeline, so it contains `x ^^^ y` for
-- Int operands. Without `HXor Int Int Int` etc., the post-assert
-- continuation theorems fail to typecheck.
--
-- The instances are emitted **conditionally** by `generate.rs`
-- only for files that contain a `Wp::AssertBitVector`. Other
-- generated files don't need them (existing tests use bitwise
-- ops only in spec mode where they're unreachable from theorems
-- today).

-- Classical logic: Tactus specs are Prop-valued (mirroring Verus's
-- spec-mode semantics), and exec fn WP goals embed them inside `if
-- <Prop> then … else …` expressions. The `if/ite` elaborator requires
-- `[Decidable P]` for each such P. For match-defined discriminators
-- like `Type.isFoo` (synthesized by `datatype_to_cmds` for multi-
-- variant inductives) Lean doesn't derive Decidable automatically, so
-- we promote all Props to Decidable via Classical. Cost: `decide`
-- won't reduce through these to concrete truth values, but exec-fn
-- automation already uses `omega` / `simp_all` rather than `decide`.
open Classical in
attribute [instance] Classical.propDecidable

-- Architecture word size for `usize` / `isize`. Kept as an opaque
-- `Nat` plus a validity axiom — concrete values come from the build
-- target. `IntegerTypeBound::ArchWordBits` renders as `arch_word_bits`;
-- `usize::MAX` / `isize::MAX` etc. reduce to expressions over it. For
-- now `type_bound_predicate` does *not* emit refinement bounds for
-- `usize`/`isize`, because tactus_auto's current toolbox can't reason
-- about symbolic exponents (`2 ^ arch_word_bits`). See DESIGN.md
-- "Fixed-width types" for the tradeoff.
axiom arch_word_bits : Nat
axiom arch_word_bits_valid : arch_word_bits = 32 ∨ arch_word_bits = 64

-- Upper bounds for `usize` / `isize`, used as the refinement target
-- by `type_bound_predicate` in sst_to_lean.
--
-- We define them in `Int` rather than `Nat` so the resulting
-- refinement (`0 ≤ e ∧ e < usize_hi` etc.) composes cleanly with
-- `e : Int` without coercion clutter. tactus_auto can't generally
-- discharge these symbolically — proofs involving `usize` / `isize`
-- arithmetic will often need an explicit `cases arch_word_bits_valid`
-- step. That's the accepted trade-off for having the bounds be
-- present at all.
noncomputable def usize_hi : Int := (2 : Int) ^ arch_word_bits
noncomputable def isize_hi : Int := (2 : Int) ^ (arch_word_bits - 1)

-- Reference-like decorations preserve type identity at the Lean level
-- so trait dispatch can distinguish `Ref A` from `A`. Verus's Z3 path
-- handles this via `context::DECORATE = true` + `sst_to_air::monotyp_to_id`,
-- which emits two-component type-IDs (`(REF, basic A)` vs
-- `(NIL_SIZED, basic A)`) so trait axioms key off the decoration.
-- Lean has no separate type-ID channel — instance resolution dispatches
-- by literal type matching — so we encode each decoration as a real
-- distinct Lean type via opaque axioms.
--
-- Without these, a non-forwarding blanket impl like
-- `impl<A: Foo> Foo for &A { spec fn foo(&self) -> int { (**self).foo() + 1 } }`
-- silently miscompiles: `peel_typ_wrappers` collapses `&Holder → Holder`
-- at the dispatch site, picks the concrete `Foo Holder` instance, and
-- the blanket's `+1` is dropped. Pinned by
-- `test_non_forwarding_blanket_over_ref_probe`.
--
-- Single-field structures with field name `deref`: the constructor is
-- `Tactus.X.mk` (taking the inner value), the projection is `.deref`
-- (or equivalently `Tactus.X.deref`). The equation `(mk x).deref = x`
-- holds DEFINITIONALLY via Lean's structure-projection rule — no axiom
-- needed, simp reduces it, rfl closes it.
--
-- Lean's typeclass dispatch treats `Tactus.Ref A` and `A` as
-- syntactically distinct heads — exactly what we need to distinguish
-- instances of `Foo &A` from `Foo A`.
--
-- `Inhabited` derives naturally given `[Inhabited A]` of the inner.
--
-- Universe-polymorphic (`A : Type u`, not `Type`): a faithful Rust→Lean
-- type map must wrap types of ANY size, including the `Type 1` indexed
-- inductives Tactus emits for cross-instantiation recursive generics
-- (e.g. `enum Mut<A> { Recurse(Box<Mut<u8>>) }` → `inductive Mut : Type
-- → Type 1`). With a monomorphic `Type → Type` wrapper, `Tactus.Box
-- (Mut Int)` failed to elaborate ("`Mut Int` has type `Type 1` but is
-- expected to have type `Type`"). `u` is auto-bound per declaration.

structure Tactus.Ref (A : Type u) where
  deref : A
  deriving Inhabited

structure Tactus.MutRef (A : Type u) where
  deref : A
  deriving Inhabited

structure Tactus.Box (A : Type u) where
  deref : A
  deriving Inhabited

structure Tactus.Rc (A : Type u) where
  deref : A
  deriving Inhabited

structure Tactus.Arc (A : Type u) where
  deref : A
  deriving Inhabited

-- `Nonempty` lifting through the wrapper family (N1,
-- DESIGN-nonempty-axioms.md). Generated theorems bind `[Nonempty Q]`
-- for their typ params (so Nonempty-bracketed axioms can instantiate
-- at Q), but an axiom slot filled with a COMPOSITE typ like
-- `Tactus.Box Q` needs `Nonempty (Tactus.Box Q)` — these instances
-- lift the param-level fact through the structure. (The `deriving
-- Inhabited` above gives `[Inhabited A] → Inhabited (Tactus.X A)`,
-- which does NOT fire from a bare `Nonempty A` binder — Nonempty
-- carries no data, so the lift needs `Classical.choice`, fine in the
-- `Nonempty` Prop.)
instance {A : Type u} [Nonempty A] : Nonempty (Tactus.Ref A) :=
  ⟨⟨Classical.choice ‹_›⟩⟩
instance {A : Type u} [Nonempty A] : Nonempty (Tactus.MutRef A) :=
  ⟨⟨Classical.choice ‹_›⟩⟩
instance {A : Type u} [Nonempty A] : Nonempty (Tactus.Box A) :=
  ⟨⟨Classical.choice ‹_›⟩⟩
instance {A : Type u} [Nonempty A] : Nonempty (Tactus.Rc A) :=
  ⟨⟨Classical.choice ‹_›⟩⟩
instance {A : Type u} [Nonempty A] : Nonempty (Tactus.Arc A) :=
  ⟨⟨Classical.choice ‹_›⟩⟩

-- SizeOf unfolding lemmas for each Tactus wrapper. Lean's auto-derived
-- `SizeOf (Tactus.X A)` for these single-field structures is
-- `sizeOf b = sizeOf b.deref + 1`, but the unfolding isn't `@[simp]`
-- by default — so generated `termination_by sizeOf` clauses for
-- recursive datatypes whose fields are wrapper-typed (`Box<Self>`,
-- `Rc<Self>`, etc.) leave the obligation
-- `sizeOf <field>.deref ≤ sizeOf <wrapper>` stuck. These `@[simp]`
-- lemmas reduce the wrapper side so the `decreasing_by` tactic
-- (`simp_all; omega`) can close.
@[simp] theorem Tactus.Ref.sizeOf_deref {A : Type u} [SizeOf A] (b : Tactus.Ref A) :
  sizeOf b = 1 + sizeOf b.deref := by cases b; rfl
@[simp] theorem Tactus.MutRef.sizeOf_deref {A : Type u} [SizeOf A] (b : Tactus.MutRef A) :
  sizeOf b = 1 + sizeOf b.deref := by cases b; rfl
@[simp] theorem Tactus.Box.sizeOf_deref {A : Type u} [SizeOf A] (b : Tactus.Box A) :
  sizeOf b = 1 + sizeOf b.deref := by cases b; rfl
@[simp] theorem Tactus.Rc.sizeOf_deref {A : Type u} [SizeOf A] (b : Tactus.Rc A) :
  sizeOf b = 1 + sizeOf b.deref := by cases b; rfl
@[simp] theorem Tactus.Arc.sizeOf_deref {A : Type u} [SizeOf A] (b : Tactus.Arc A) :
  sizeOf b = 1 + sizeOf b.deref := by cases b; rfl

-- Guard hypotheses through Prop `∨`/`∧` for termination proofs (F2c,
-- DESIGN-lean-all-proofs-followons.md). Verus's spec `||`/`&&` are
-- short-circuit for well-definedness — a recursive call in the RHS is
-- checked under the LHS guard — but Lean's termination elaborator
-- provides hypotheses only for control flow it recognizes (core's
-- `wf_preprocess` set rewrites `ite → dite` and nothing else), so
-- `A ∨ (B ∧ f (shrink x))` yields a decreasing goal with NO `¬A`/`B`
-- in context, unprovable however smart the tactic. These two proved
-- rewrites extend the same sanctioned mechanism core uses: during
-- termination elaboration only, `∨`/`∧` become the equivalent `dite`
-- so the elaborator threads the guards. Definitional equations
-- (`f.eq_def`, `unfold f`, simp) keep the user's original `∨`/`∧`
-- shape — verified empirically — so closers and humans see exactly
-- what was written. `binderNameHint` keeps the hypothesis anonymous
-- (inaccessible), matching core's `ite_eq_dite` behavior; the
-- `decreasing_by` rungs use `simp_all`/`omega`, which read
-- inaccessibles fine. Classical decidability is already ambient in
-- generated code (if-on-Prop is pervasive).
open Classical in
@[wf_preprocess] theorem Tactus.or_eq_dite {a b : Prop} :
    (a ∨ b) = (dite a (fun _ => True) (fun h => binderNameHint h () b)) := by
  by_cases h : a <;> simp [h, binderNameHint]

open Classical in
@[wf_preprocess] theorem Tactus.and_eq_dite {a b : Prop} :
    (a ∧ b) = (dite a (fun h => binderNameHint h () b) (fun _ => False)) := by
  by_cases h : a <;> simp [h, binderNameHint]

-- `Tactus.strGetChar s i` is the i-th Unicode codepoint of `s` as a
-- `Nat`. The lowering target for Verus's `verus_builtin::strslice_get_char`
-- (VIR `BinaryOp::StrGetChar`, surface syntax `strslice_get_char(s, i)`).
--
-- Verus renders `&str` as Lean `String` and `char` as `Nat` (Verus's
-- `IntRange::Char` maps to `Nat` in `to_lean_type.rs`). So the
-- signature must be `String → Int → Nat`.
--
-- We can't use Lean's `String.get` directly: that takes a `String.Pos`
-- (a *byte* offset, not a codepoint index) and returns Lean's `Char`.
-- Verus's semantics is codepoint-indexed. `s.data : List Char` is the
-- underlying codepoint list, so `s.data[i.toNat]!` gives the i-th
-- codepoint (panicking out-of-bounds via the `GetElem!` instance);
-- `.toNat` unwraps to the integer value.
--
-- The panic-on-OOB is fine because Tactus only verifies goals, never
-- executes the generated Lean. Out-of-bounds is unspecified, matching
-- Verus's spec semantics.
def Tactus.strGetChar (s : String) (i : Int) : Nat :=
  (s.data[i.toNat]!).toNat

-- Height-ordering relation for Verus's `BinaryOp::HeightCompare` (the
-- fn-level termination measure). The VIR-AST renderer special-cases
-- int operands (direct `<`) and datatype operands (`T.height`
-- comparison); for opaque / cross-crate types that have no `.height`
-- companion — notably `vstd::seq::Seq`, whose `axiom_seq_index_decreases`
-- states `s[i]` is height-smaller than `s` — it falls back to this
-- relation. Left uninterpreted (an `axiom`, not a `def`): it carries
-- the termination fact faithfully without committing to a height model
-- for opaque types. The two operands have distinct types (`s[i] : A`
-- vs `s : Seq A`), hence the two type parameters.
axiom Tactus.heightLt {α : Type u} {β : Type v} (a : α) (b : β) : Prop

-- Spec-mode array indexing (`BinaryOp::Index` — `a[i]` on `[T; N]` in
-- spec code, and vstd's `array_view` body `Seq::new(N, |i| a[i])`).
-- `[T; N]` renders as Lean core's length-indexed `Vector α n`; the
-- length is implicit here so the rendered call stays `Tactus.index a i`.
-- Left uninterpreted: vstd's array axioms (`lemma_array_index`,
-- `array_view` roundtrips) give it in-range meaning; out-of-range is
-- unspecified, matching Verus's treatment of spec indexing as a total
-- but unconstrained function. `[Nonempty α]`-bracketed (N2,
-- DESIGN-nonempty-axioms.md): an unbracketed version inhabits EVERY
-- α (the empty vector inhabits `Vector Empty 0`, so `Tactus.index
-- (α := Empty) ⟨#[], rfl⟩ 0 : Empty` derived False — the
-- test_soundness_hole_prelude exploit pin). Under the bracket the
-- axiom is satisfiable, matching Verus's spec-types-are-inhabited
-- guarantee where it actually holds instead of globally axiomatizing
-- it. Generated theorems that index at a typ param carry the matching
-- `[Nonempty]` binder (nonempty.rs Seed 3).
axiom Tactus.index {α : Type u} [Nonempty α] {n : Nat} (a : Vector α n) (i : Int) : α

-- `has_resolved(x)` — Verus's mutable-reference resolution predicate
-- (`UnaryOpr::HasResolved`). For `&mut T` it states the prophetic value
-- equals the current value; for primitives it's trivially true; for
-- datatypes it's recursive. Tactus doesn't model resolution (it drops
-- `assume(has_resolved(..))` synthetic statements), so the predicate is
-- rendered as an uninterpreted Prop rather than collapsed to its bare
-- argument — leaving its truth abstract keeps cross-crate axioms that
-- mention it (e.g. vstd's `axiom_vec_has_resolved`) well-typed and sound
-- (no assumption that it holds or fails). Same pattern as `heightLt`.
axiom Tactus.hasResolved {α : Type u} (a : α) : Prop

-- ── Axiom-closure enforcement (DESIGN-axiom-closure-check.md) ────────
-- `#tactus_check_axioms thm [ax₁, …]` computes `thm`'s axiom closure
-- (the same walk `#print axioms` uses) and FAILS ELABORATION if the
-- closure contains anything outside:
--   • Lean's classical core (propext, Classical.choice, Quot.sound),
--   • this prelude's own axioms (hardcoded HERE so they version with
--     this file — the olean content-hash rebuild keeps the command
--     and the axiom set in sync by construction),
--   • compiled-execution licenses (Lean.ofReduceBool /
--     Lean.trustCompiler — what bv_decide's native LRAT check needs;
--     allowed-but-inventoried, the design doc's §3 policy knob),
--   • the explicit per-call expected list (the crate's Boundary set —
--     dependency axioms the generator itself emitted).
-- `sorryAx` in the closure is ALWAYS fatal. Subset check, not
-- equality: a proof that doesn't use a declared dependency is fine.
open Lean Elab Command in
elab "#tactus_check_axioms" thm:ident "[" expected:ident,* "]" : command => do
  liftTermElabM do
    let name ← realizeGlobalConstNoOverloadWithInfo thm
    let axioms ← collectAxioms name
    let base : List Name :=
      [``propext, ``Classical.choice, ``Quot.sound,
       `arch_word_bits, `arch_word_bits_valid,
       `Tactus.heightLt, `Tactus.index, `Tactus.hasResolved,
       ``Lean.ofReduceBool, ``Lean.trustCompiler]
    let mut allowed : NameSet := {}
    for n in base do
      allowed := allowed.insert n
    for e in expected.getElems do
      -- Expected names may be namespace-relative (the generator emits
      -- the check inside the crate namespace) — resolve like the thm.
      let n ← realizeGlobalConstNoOverloadWithInfo e
      allowed := allowed.insert n
    for ax in axioms do
      if ax == ``sorryAx then
        throwErrorAt thm "tactus: proof of {name} contains sorry"
      unless allowed.contains ax do
        throwErrorAt thm
          "tactus: proof of {name} rests on undeclared axiom {ax} — \
           if this is a deliberate trust extension, it must be declared \
           in the expected list (see DESIGN-axiom-closure-check.md)"
