import TactusDefs_lib_exec
set_option linter.unusedVariables false
set_option autoImplicit false
set_option maxRecDepth 8000

-- b70/b71 close-out suite (endgame A1), GENERATED by gen.py from the
-- LIVE fixture certs. See gen.py docstring for the claim table.

-- Probe-local per-goal accessor (Nat-structural; Box via .deref).
@[reducible] noncomputable def gl_nth (l : lib.GoalList) : Nat → Option lib.GoalData :=
  fun n => match n, l with
  | 0, lib.GoalList.Cons g _ => some g.deref
  | Nat.succ m, lib.GoalList.Cons _ t => gl_nth t.deref m
  | _, lib.GoalList.Nil => none

@[reducible] noncomputable def gl_nth_eq (a b : lib.GoalList) (n : Nat) : Nat :=
  match gl_nth a n, gl_nth b n with
  | some x, some y => lib.goal_eq x y
  | _, _ => 2

-- ── b71: use_clamped — ∀-path Call post frame ──
@[reducible] def uc_ctx : lib.FnCtxData := (lib.FnCtxData.mk lib.BinderList.Nil (lib.BinderList.Cons 0 1 (Tactus.Box.mk lib.BinderList.Nil)) (lib.ParamBoundList.Bound 3 2 (Tactus.Box.mk lib.ParamBoundList.Nil)) (lib.BinderList.Cons 5 4 (Tactus.Box.mk lib.BinderList.Nil)) (lib.LeafList.Cons 6 (Tactus.Box.mk lib.LeafList.Nil)) 1)
@[reducible] def uc_sst : lib.StmData := (lib.StmData.Seq (Tactus.Box.mk (lib.StmData.Call (Tactus.Box.mk lib.RawExpList.Nil) (Tactus.Box.mk (lib.FrameList.FBind 10 1 (Tactus.Box.mk (lib.FrameList.FHyp 11 14 0 (Tactus.Box.mk (lib.FrameList.FHyp 12 13 0 (Tactus.Box.mk lib.FrameList.FNil))))))))) (Tactus.Box.mk (lib.StmData.Ret (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Span 9 (Tactus.Box.mk (lib.RawExp.BinOp 5 lib.TypData.TyBool (Tactus.Box.mk (lib.RawExp.Var 8 lib.TypData.TyInt)) (Tactus.Box.mk (lib.RawExp.Var 0 lib.TypData.TyInt)))))) (Tactus.Box.mk lib.RawExpList.Nil))) (lib.RetBind.RetLetH 8 1 10 16 15))))
@[reducible] def uc_goals : lib.GoalList := lib.GoalList.Cons (Tactus.Box.mk (lib.GoalData.All 0 1 (Tactus.Box.mk (lib.GoalData.All 3 2 (Tactus.Box.mk (lib.GoalData.All 5 4 (Tactus.Box.mk (lib.GoalData.All 10 1 (Tactus.Box.mk (lib.GoalData.All 11 14 (Tactus.Box.mk (lib.GoalData.All 12 13 (Tactus.Box.mk (lib.GoalData.All 8 1 (Tactus.Box.mk (lib.GoalData.All 16 15 (Tactus.Box.mk (lib.GoalData.LeafE (lib.ExprData.SpanMark 9 (Tactus.Box.mk (lib.ExprData.BinOp 5 (Tactus.Box.mk (lib.ExprData.Atom 8)) (Tactus.Box.mk (lib.ExprData.Atom 0))))))))))))))))))))))) (Tactus.Box.mk lib.GoalList.Nil)
@[reducible] def uc_sst_dropbound : lib.StmData := (lib.StmData.Seq (Tactus.Box.mk (lib.StmData.Call (Tactus.Box.mk lib.RawExpList.Nil) (Tactus.Box.mk (lib.FrameList.FBind 10 1 (Tactus.Box.mk (lib.FrameList.FHyp 12 13 0 (Tactus.Box.mk lib.FrameList.FNil))))))) (Tactus.Box.mk (lib.StmData.Ret (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Span 9 (Tactus.Box.mk (lib.RawExp.BinOp 5 lib.TypData.TyBool (Tactus.Box.mk (lib.RawExp.Var 8 lib.TypData.TyInt)) (Tactus.Box.mk (lib.RawExp.Var 0 lib.TypData.TyInt)))))) (Tactus.Box.mk lib.RawExpList.Nil))) (lib.RetBind.RetLetH 8 1 10 16 15))))
@[reducible] def uc_sst_swapped : lib.StmData := (lib.StmData.Seq (Tactus.Box.mk (lib.StmData.Call (Tactus.Box.mk lib.RawExpList.Nil) (Tactus.Box.mk (lib.FrameList.FBind 10 1 (Tactus.Box.mk (lib.FrameList.FHyp 12 13 0 (Tactus.Box.mk (lib.FrameList.FHyp 11 14 0 (Tactus.Box.mk lib.FrameList.FNil))))))))) (Tactus.Box.mk (lib.StmData.Ret (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Span 9 (Tactus.Box.mk (lib.RawExp.BinOp 5 lib.TypData.TyBool (Tactus.Box.mk (lib.RawExp.Var 8 lib.TypData.TyInt)) (Tactus.Box.mk (lib.RawExp.Var 0 lib.TypData.TyInt)))))) (Tactus.Box.mk lib.RawExpList.Nil))) (lib.RetBind.RetLetH 8 1 10 16 15))))
-- baseline: the ∀-path caller bridge-closes post-b74.
example : lib.goals_eq (lib.ref_wp uc_ctx uc_sst) uc_goals = 1 := by decide
-- kill A: dropping the ret-bound FHyp flips.
example : lib.goals_eq (lib.ref_wp uc_ctx uc_sst_dropbound) uc_goals = 0 := by decide
-- kill B: swapping ret-bound <-> ens FHyps flips.
example : lib.goals_eq (lib.ref_wp uc_ctx uc_sst_swapped) uc_goals = 0 := by decide

-- ── b70: vec_read — generic Call, per-goal ──
@[reducible] def vr_ctx : lib.FnCtxData := (lib.FnCtxData.mk lib.BinderList.Nil (lib.BinderList.Cons 0 1 (Tactus.Box.mk (lib.BinderList.Cons 2 3 (Tactus.Box.mk lib.BinderList.Nil)))) (lib.ParamBoundList.NoBound (Tactus.Box.mk (lib.ParamBoundList.Bound 5 4 (Tactus.Box.mk lib.ParamBoundList.Nil)))) (lib.BinderList.Cons 7 6 (Tactus.Box.mk lib.BinderList.Nil)) (lib.LeafList.Cons 8 (Tactus.Box.mk lib.LeafList.Nil)) 1)
@[reducible] def vr_sst : lib.StmData := (lib.StmData.Seq (Tactus.Box.mk (lib.StmData.Call (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Var 16 lib.TypData.TyBool)) (Tactus.Box.mk lib.RawExpList.Nil))) (Tactus.Box.mk (lib.FrameList.FLetH 17 19 18 21 20 (Tactus.Box.mk lib.FrameList.FNil))))) (Tactus.Box.mk (lib.StmData.Ret (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Span 15 (Tactus.Box.mk (lib.RawExp.BinOp 0 lib.TypData.TyBool (Tactus.Box.mk (lib.RawExp.Var 10 lib.TypData.TyInt)) (Tactus.Box.mk (lib.RawExp.CallN 11 lib.TypData.TyInt (Tactus.Box.mk (lib.RawList.Cons (Tactus.Box.mk (lib.RawExp.Call 12 (lib.TypData.TyNamed 13) (Tactus.Box.mk (lib.RawExp.Var 0 (lib.TypData.TyRef 14))) (lib.TypData.TyRef 14))) (Tactus.Box.mk (lib.RawList.Cons (Tactus.Box.mk (lib.RawExp.Var 2 lib.TypData.TyNat)) (Tactus.Box.mk lib.RawList.Nil))))))))))) (Tactus.Box.mk lib.RawExpList.Nil))) (lib.RetBind.RetLetH 10 23 22 25 24))))
@[reducible] def vr_goals : lib.GoalList := lib.GoalList.Cons (Tactus.Box.mk (lib.GoalData.All 0 1 (Tactus.Box.mk (lib.GoalData.All 2 3 (Tactus.Box.mk (lib.GoalData.All 5 4 (Tactus.Box.mk (lib.GoalData.All 7 6 (Tactus.Box.mk (lib.GoalData.LeafE (lib.ExprData.Atom 16))))))))))) (Tactus.Box.mk (lib.GoalList.Cons (Tactus.Box.mk (lib.GoalData.All 0 1 (Tactus.Box.mk (lib.GoalData.All 2 3 (Tactus.Box.mk (lib.GoalData.All 5 4 (Tactus.Box.mk (lib.GoalData.All 7 6 (Tactus.Box.mk (lib.GoalData.All 17 19 (Tactus.Box.mk (lib.GoalData.All 21 20 (Tactus.Box.mk (lib.GoalData.All 10 23 (Tactus.Box.mk (lib.GoalData.All 25 24 (Tactus.Box.mk (lib.GoalData.LeafE (lib.ExprData.SpanMark 15 (Tactus.Box.mk (lib.ExprData.BinOp 0 (Tactus.Box.mk (lib.ExprData.Atom 10)) (Tactus.Box.mk (lib.ExprData.AppN 11 (Tactus.Box.mk (lib.ExprList.Cons (Tactus.Box.mk (lib.ExprData.App 12 (Tactus.Box.mk (lib.ExprData.Atom 0)))) (Tactus.Box.mk (lib.ExprList.Cons (Tactus.Box.mk (lib.ExprData.Cast lib.CastKind.NatToInt (Tactus.Box.mk (lib.ExprData.Atom 2)))) (Tactus.Box.mk lib.ExprList.Nil)))))))))))))))))))))))))))) (Tactus.Box.mk lib.GoalList.Nil)))
@[reducible] def vr_sst_reqmut : lib.StmData := (lib.StmData.Seq (Tactus.Box.mk (lib.StmData.Call (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Var 9999 lib.TypData.TyBool)) (Tactus.Box.mk lib.RawExpList.Nil))) (Tactus.Box.mk (lib.FrameList.FLetH 17 19 18 21 20 (Tactus.Box.mk lib.FrameList.FNil))))) (Tactus.Box.mk (lib.StmData.Ret (Tactus.Box.mk (lib.RawExpList.Cons (Tactus.Box.mk (lib.RawExp.Span 15 (Tactus.Box.mk (lib.RawExp.BinOp 0 lib.TypData.TyBool (Tactus.Box.mk (lib.RawExp.Var 10 lib.TypData.TyInt)) (Tactus.Box.mk (lib.RawExp.CallN 11 lib.TypData.TyInt (Tactus.Box.mk (lib.RawList.Cons (Tactus.Box.mk (lib.RawExp.Call 12 (lib.TypData.TyNamed 13) (Tactus.Box.mk (lib.RawExp.Var 0 (lib.TypData.TyRef 14))) (lib.TypData.TyRef 14))) (Tactus.Box.mk (lib.RawList.Cons (Tactus.Box.mk (lib.RawExp.Var 2 lib.TypData.TyNat)) (Tactus.Box.mk lib.RawList.Nil))))))))))) (Tactus.Box.mk lib.RawExpList.Nil))) (lib.RetBind.RetLetH 10 23 22 25 24))))
-- baseline: goal 0 (Call PRECONDITION, generic instantiation) closes.
example : gl_nth_eq (lib.ref_wp vr_ctx vr_sst) vr_goals 0 = 1 := by decide
-- kill: perturbing the transcribed req atom flips goal 0.
example : gl_nth_eq (lib.ref_wp vr_ctx vr_sst_reqmut) vr_goals 0 = 0 := by decide
-- A7 TRIPWIRE: goal 1 (Ret) is the documented stage-B honest-fail
-- (view-call deref + Int.ofNat CallN coercion). When the A7 vocabulary
-- lands and this closes, this example fails loud — replace with a
-- close+kill pair. Never a silent cap (P2).
example : gl_nth_eq (lib.ref_wp vr_ctx vr_sst) vr_goals 1 = 0 := by decide
