/// The minimal Tactus prelude for Lean.
///
/// This is prepended to every generated .lean file. It sets Lean options
/// and will eventually define Verus built-in types (Seq, Set, etc.).
///
/// For Phase 1, it's minimal — just option settings.
pub const TACTUS_PRELUDE: &str = r#"
-- Auto-generated by Tactus. Do not edit.
set_option linter.unusedVariables false
set_option maxHeartbeats 800000

"#;
